services:
  api-gateway:
    build:
      context: ./  # Set context to the root directory
      dockerfile: ./backend/apps/api-gateway/Dockerfile
    volumes:
      - ./backend:/usr/src/app  # Sync the backend directory
      - /usr/src/app/node_modules    
    ports:
      - "3001:3001"  # Expose API Gateway on port 3001
    environment:
      - NODE_ENV=development
    depends_on:
      - event-management

  event-management:
    build:
      context: ./
      dockerfile: ./backend/apps/event-management/Dockerfile  
    volumes:
      - ./backend:/usr/src/app  # Sync the backend directory
      - /usr/src/app/node_modules  # Prevent overwriting node_modules  
    ports:
      - "3002:3002"  # Expose Event Management on port 3002
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./  # Set context to the root directory
      dockerfile: ./frontend/Dockerfile  # Specify Dockerfile path
    volumes:
      - ./frontend:/usr/src/app  # Sync the frontend directory
      - /usr/src/app/node_modules  # Prevent overwriting node_modules  
    ports:
      - "3000:3000"  # Expose the front-end on port 3000
    environment:
      - NODE_ENV=development
    depends_on:
      - api-gateway